name: Build
on: [push,workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - id: Build
      uses: depuits/MetalsmithPagesAction@0.0.1
      with:
        username: 'huurfeestartikelen-be'
        reponame: 'huurfeestartikelen-be.github.io'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
